#!/usr/bin/python3

import sys

def factorize(nb):
    factors = []
    x = 2
    while x * x <= nb:
        while nb % x == 0:
            factors.append(x)
            nb //= x
        x += 1
    if nb > 1:
        factors.append(nb)
    return factors

def check_factor(args):
    if len(args) != 1:
        count = 0
        nb2 = 1
        for a in args:
            if count > 0:
                nb2 *= int(a)
            count += 1
    else:
        nb2 = int(args[0])

    nb1 = int(args[0])
    
    rst = int(nb2 > nb1)
    
    if rst == 1:
        numcp = nb1
        nb1 = nb2
        nb2 = numcp

    print(f"{nb1}={nb2}*{nb1//nb2}")

if len(sys.argv) != 2:
    print('Usage: python script.py <file>')
    sys.exit(1)

input_filename = sys.argv[1]

try:
    with open(input_filename, 'r') as file:
        for li in file:
            nb = int(li.strip())
            factors = factorize(nb)
            check_factor(factors)
except FileNotFoundError:
    print(f"Error: Can't open file '{input_filename}'")
    sys.exit(1)
